---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kuard
spec:
  replicas: 2
  template:
    metadata:
      labels: 
        app: kuard
        version: "2"
    spec:
      containers:
        - name: kuard
          image: "105926288004.dkr.ecr.eu-central-1.amazonaws.com/my_repo:green"
...